spring:
  datasource:
    username: root
    password: liuyue
    url: jdbc:mysql://localhost:3306/orderyue
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  type-aliases-package: com.easy.bean
logging:
  level:
    com.easy.dao: debug
server:
  port: 80